### ISSUE TITLE
Consider adding biber to pre-installed packages

### ISSUE THREAD

**Issue by evilstiefel** [blang/latex-docker#10]
Thanks for this image, works just fine! I've started using it to kick off automatic builds of the PDF and publishing it using Gitlab-CI.

Since this image now is even sort of officially mentioned in the template for such tasks in the Gitlab documentation, why not make it more useable for biblatex-workflows by adding biber via apt?

Otherwise, any compilation will fail with the missing dependency.

**Comment by janstuemmel** [comment]
duplicate #5 

i have created one with biber installed https://github.com/janstuemmel/docker-latex

just change your yml file to:
```yml
image: janstuemmel/docker-latex

build:
  script:
    - latexmk -pdf
  artifacts:
    paths:
      - "*.pdf"
```
