### ISSUE TITLE
URGENT | BibTeX and Glossary Problems

### ISSUE THREAD

**Issue by tutods** [blang/latex-docker#31]
Hi
I have my pipeline like this:
```
image: blang/latex:ctanfull

build:
  script:
    - cd latex_project_folder/
    - latexmk -bibtex -pdf
  artifacts:
    paths:
      - "*.pdf"
```

But my pipeline fail all time, I think is because the Bitbtex.
Any solution?
